version: '3.7'
volumes:
  data:
services:
  db:
    image: mysql:5.7
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    container_name: db_si_atividade01
    volumes:
      - ./docs/database/:/docker-entrypoint-initdb.d
    networks:
      mysql-compose-dev:
        ipv4_address: 13.0.0.2
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: kinuca01
      MYSQL_DATABASE: db_si_atividade01

networks:
  mysql-compose-dev:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 13.0.0.1/16
